// Generated by CoffeeScript 2.5.1
(function() {
  var active, canvas, ctx, drawHeart, drawScene, drawUI, l, lives, x, y;

  canvas = document.getElementById("game");

  ctx = canvas.getContext("2d");

  canvas.height = 300;

  canvas.width = 700;

  ctx.msImageSmoothingEnabled = false;

  ctx.imageSmoothingEnabled = false;

  x = (canvas.width / 2) - 20;

  y = canvas.height / 2;

  lives = 3;

  l = 0;

  active = function() {
    ctx.beginPath();
    ctx.strokeStyle = "white";
    ctx.lineWidth = 5;
    return ctx.strokeRect(5, 5, canvas.width - 10, canvas.height - 10);
  };

  drawHeart = function() {
    var height, img, width;
    width = 30;
    height = 30;
    ctx.beginPath();
    img = new Image();
    img.src = "assets/heart.png";
    return ctx.drawImage(img, x, y, width, height);
  };

  drawUI = function() {
    var heart, height, i, life, ref, results, width;
    heart = new Image();
    heart.src = 'assets/life.png';
    width = 20;
    height = 20;
    ctx.beginPath();
    results = [];
    for (life = i = 1, ref = lives; (1 <= ref ? i <= ref : i >= ref); life = 1 <= ref ? ++i : --i) {
      results.push(ctx.drawImage(heart, 0 + (life * 20), 17, width, height));
    }
    return results;
  };

  drawScene = function() {
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    active();
    if (l === 30) {
      lives = 2;
    }
    if (l === 60) {
      lives = 1;
    }
    if (l === 90) {
      lives = 0;
    }
    drawUI();
    drawHeart();
    return l = l + 1;
  };

  setInterval(drawScene, 100);

}).call(this);
